#ifndef __GAME_PLAYER_H__
#define __GAME_PLAYER_H__

#include <stdint.h>
#include <uuid/uuid.h>
#include "cl_game_state.h"
#include "cl_game_object.h"
#include "cl_graph.h"
#include "cl_fonts.h"
#include "network.h"

struct player
{
  // Identification
  char *username;
  char *password;

  uuid_t uuid; // unique uuid generated by client

  // Position
  int16_t x_coord;
  int16_t y_coord;

  uint8_t dimension;

  ///////////////////////////////////////
  //                                   //
  //    ____   _|__   ____    ____     //
  //  _|    | |    | |    |_ |    |    //
  //   |____| |____| |____|  |____|    //
  //                            |      //
  //                                   //
  ///////////////////////////////////////

  // State
  uint8_t life;

  // Network
  struct sockaddr_in *cliaddr;
  struct sockaddr_in *servaddr; // For client side
  int cl_socket;
  int serv_socket; // For client side

  uint8_t connected_to_server; // For client side

  // Graphics
  struct game_object *game_object; // link to game object
                                   // to have possibility
                                   // to update position of player

  // Link to game state
  struct game_state *game_state;
};

struct player *create_new_player_from_server(char *packet);
struct player *create_new_player(char *username, struct game_state *game_state_ptr);
void set_player_username(struct player *player, char *username);
void draw_player(struct player *p);
void draw_players(struct game_state *game_state_ptr);
void print_players(struct game_state *game_state_ptr);

#endif